name: My First GitHub Action

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello from GitHub Actions!"

      - name: Check Linux
        run: |
          echo "Running on:"
          uname -a

      - name: Check Docker
        run: docker --version
